Fix Coverity warnings
OpenSCAP/openscap pull request #1617
Opened 2020-10-06 11:35 UTC by jan-cerny

Addressing multiple Coverity defects similar to this one:
Defect type: CHECKED_RETURN
check_return: Calling "curl_easy_setopt(curl, _curl_opt, _curl_trace)"
without checking return value. This library function may fail and return
an error code.

2020-10-08 09:20 UTC, matejak commented
test this please

2020-10-12 08:45 UTC, matusmarhefka requested changes

2020-10-12 08:45 UTC, matusmarhefka commented on src/common/oscap_acquire.c
> +	if (res != 0) {
We should also add `curl_easy_cleanup(curl)` in these newly added ifs to free the allocated structure by the `curl_easy_init` function.

2020-10-26 10:13 UTC, jan-cerny commented
I have added curl_easy_cleanup.

2020-10-27 06:58 UTC, evgenyz commented
LGTM

2020-10-27 06:58 UTC, merged