Add dpkg version comparison algorithm
OpenSCAP/openscap pull request #1662
Opened 2020-12-09 15:04 UTC by dodys

This commit move away from using rpm version comparison algorithm for
debian based distros and at the same time fixes false positives that
happen when the revision of a package contains a '~'.

I've based it on maint-1.3, but this could certainly go to master and even maint-1.2.

2020-12-09 16:19 UTC, redhatrises commented
@openscap-ci test this please

2020-12-10 08:09 UTC, evgenyz requested changes
Thank you for your contribution! We will gladly accept your PR after minor problem fixes (resource management and formatting).

2020-12-10 08:09 UTC, evgenyz commented on src/OVAL/results/oval_cmp_evr_string.c
> +                     struct dpkg_version *b)
Please, don't use tabs for this kind of code formatting.

2020-12-10 08:09 UTC, evgenyz commented on src/OVAL/results/oval_cmp_evr_string.c
> +	}
It feels like `switch` would look better here.

2020-12-10 14:30 UTC, dodys commented
Thanks for the review, I just added a new commit addressing your points.

2020-12-10 23:51 UTC, evgenyz commented
Thank you!

2020-12-10 23:52 UTC, evgenyz approved these changes

2020-12-10 23:52 UTC, merged