Add new Dockerfile which can run test suite for PRs
OpenSCAP/openscap pull request #1777
Opened 2021-06-30 11:51 UTC by matusmarhefka

The new Dockerfile might be useful for debugging purposes or just for
running the test suite isolated from a host system. It runs the test suite
exactly the same as in GH action and it can be parametrized to run
for a specific GitHub PR.

2021-07-07 06:59 UTC, jan-cerny requested changes

2021-07-07 06:59 UTC, jan-cerny commented on Dockerfiles/test_suite
> +RUN git clone https://github.com/OpenSCAP/openscap
Add `--recurse-submodules` to build and test also the yamlfilecontent probe.

```suggestion
RUN git clone --recurse-submodules https://github.com/OpenSCAP/openscap
```

2021-07-16 08:32 UTC, jan-cerny commented
@matusmarhefka 
I have tried to use it to test PR #1781 and I can see that there is some fail:

```
183/258 Test #183: probes/file/test_probes_file_multiple_file_paths.sh ................................***Failed    0.07 sec
/bin/strace
/bin/strace: test_ptrace_get_syscall_info: PTRACE_TRACEME: Operation not permitted
/bin/strace: ptrace(PTRACE_TRACEME, ...): Operation not permitted
/bin/strace: PTRACE_SETOPTIONS: Operation not permitted
/bin/strace: detach: waitpid(38891): No child processes

```

Do I need to run podman as a `root` user?

2021-07-16 08:51 UTC, matusmarhefka commented
> @matusmarhefka
> I have tried to use it to test PR #1781 and I can see that there is some fail:
> 
> ```
> 183/258 Test #183: probes/file/test_probes_file_multiple_file_paths.sh ................................***Failed    0.07 sec
> /bin/strace
> /bin/strace: test_ptrace_get_syscall_info: PTRACE_TRACEME: Operation not permitted
> /bin/strace: ptrace(PTRACE_TRACEME, ...): Operation not permitted
> /bin/strace: PTRACE_SETOPTIONS: Operation not permitted
> /bin/strace: detach: waitpid(38891): No child processes
> ```
> 
> Do I need to run podman as a `root` user?

Hmm, looks like a missing capability? Try `podman run --cap-add=SYS_PTRACE ...`.

2021-07-16 08:52 UTC, jan-cerny commented
> Do I need to run podman as a root user?

You probably don't have to because the same problem occurs also when you run it as a root. It can be some missing permission such as capability?

2021-07-16 09:13 UTC, jan-cerny commented
> Hmm, looks like a missing capability? Try podman run --cap-add=SYS_PTRACE ....

Yes! That was it! It fixed the problem for me.

2021-07-16 10:26 UTC, jan-cerny approved these changes

2021-07-16 10:26 UTC, merged