PCRE2
OpenSCAP/openscap pull request #2015
Opened 2023-08-28 17:58 UTC by evgenyz

TBD

2023-08-28 18:01 UTC, evgenyz commented on src/OVAL/probes/oval_fts.c
> -	case PCRE_ERROR_BADPARTIAL:
We don't need that case anymore. Any recent version of the library does not have limits on partial matches. This is just a dead code block now.

2023-09-01 07:29 UTC, jan-cerny commented
/packit retest-failed

2023-09-04 11:05 UTC, evgenyz commented
/packit retest-failed

2023-09-04 11:05 UTC, evgenyz commented
/packit rebuild-failed

2023-09-04 12:11 UTC, evgenyz commented on tests/probes/textfilecontent54/test_recursion_limit.sh
> +grep -q "Function oscap_pcre_exec() failed to match a regular expression with return code -21" $stderr
No, but `oscap_pcre_exec` will.

2023-09-04 13:13 UTC, evgenyz commented on openscap.spec
> +BuildRequires:  pcre2-devel
I confined it to Fedoras + upstream Ubuntu.

2023-09-04 19:47 UTC, evgenyz commented on openscap.spec
> +    -DWITH_PCRE2=ON \
Ditto, Fedora+Ubuntu only.

2023-09-04 22:02 UTC, evgenyz commented on docs/developer/developer.adoc
> +  for match in pcre_exec/pcre2_match calls in textfilecontent(54) probes.
By default the build system will try to find and link with PCRE1 library (minor version, we should not break the behavior). Changing the requirements in the documentation could bring a lot of confusion.

2023-09-04 22:05 UTC, evgenyz commented on tests/API/probes/oval_fts_list.c
> +	oscap_set_verbose(NULL, NULL);
The first `NULL` in `oscap_set_verbose` sets the default log level (WARNING) and the second sets the default output (STDERR). Without this change the test binary won't display any logs. Very inconvenient.

2023-09-04 22:07 UTC, evgenyz commented on src/common/oscap_pcre.c
> +	dD("pcre2_compile_8: patt=%s", pattern);
I have a feeling that we will need these regex-related logs for debugging problems very soon. It's debug level anyways.

2023-09-04 22:08 UTC, evgenyz commented on src/common/oscap_pcre.c
> +oscap_pcre_t* oscap_pcre_compile(const char *pattern, oscap_pcre_options_t options,
Fixed.

2023-09-05 06:28 UTC, jan-cerny requested changes
Overall, the changes look OK to me. Thanks for your patch!

I have reviewed the build and test results and I have seen that we build and test with PCRE2 in GH CI.

Regarding the Developer Guide, I understand your point, but I think that you should mention it there that there is an option to build the project with PCRE2. You can also make the Developer Guide ready for the situation that PCRE will be sunset in future Fedora.

Lastly, please fix the Windows build, we have committed that we will make sure that OpenSCAP is buildable on Windows for the entire lifetime of version 1.3.x (https://github.com/OpenSCAP/openscap/blob/maint-1.3/docs/windows.md). I think it'd be possible to replace the `bzero()` by `calloc()`.

2023-09-05 11:24 UTC, merged