Select rules based on reference
OpenSCAP/openscap pull request #2070
Opened 2024-01-08 16:11 UTC by jan-cerny

This PR introduces a new option `--reference` that allows users to filter rules base on rule reference. This is useful to evaluate compliance with a particular policy requirement.

This feature needs SCAP content to contain reference URI-to-title mapping within the `xccdf:Benchmark` element. The ComplianceAsCode content upstream project started to provide this mapping in the SCAP content recently, starting from 62513c391dc5a3fafd12741bd02565ca0e1e8db2.

To support the easier experience with this feature, also a new option `--references` to the `oscap info` module has been added, this option extends the output of the command by listing all available reference names.

Fixes: https://issues.redhat.com/browse/RHEL-1479

2024-01-09 17:08 UTC, Mab879 requested changes
Thanks for the PR.

Please take a look at my comments.

2024-01-09 17:08 UTC, Mab879 commented on utils/oscap-xccdf.c
> +		"   --reference <URL=ID>          - Evaluate only rules that have the given reference.\n"
Should this a `:`?

2024-01-09 17:08 UTC, Mab879 commented on src/XCCDF_POLICY/xccdf_policy.c
> +	char **split = oscap_split(reference_parameter_dup, ":");
So I can get a segfault if I run `./oscap_wrapper xccdf eval --profile stig --reference 'stigid'  [datastream]`. There should be some error handling for this case.

2024-01-10 07:59 UTC, jan-cerny commented
I have fixed the segfault. I have fixed the help text.

2024-01-10 15:26 UTC, Mab879 approved these changes
LGTM.

Thanks.

2024-01-10 15:28 UTC, Mab879 requested changes
Can you please review the testing farm failure?

2024-01-10 16:08 UTC, jan-cerny commented
It's the  probe_behavior/collect_limit.sh which fails randomly from time to time

2024-01-10 16:08 UTC, jan-cerny commented
/packit retest-failed

2024-01-10 16:45 UTC, merged