Remove the option to build with PCRE2
OpenSCAP/openscap pull request #2116
Opened 2024-05-31 15:46 UTC by Mab879

The project will now only built with PCRE2 only.

2024-06-03 13:53 UTC, jan-cerny requested changes

2024-06-03 13:53 UTC, jan-cerny commented on cmake/FindPCRE.cmake
> -# PCRE_LIBRARIES	- List of libraries when using pcre.
I have found `PCRE_LIBRARIES` in multiple places in the project, they should be removed as well.

2024-06-03 13:53 UTC, jan-cerny commented on docs/developer/developer.adoc
>  Fedora/RHEL — pcre2-devel.
please update all the install commands above

2024-06-05 07:58 UTC, jan-cerny approved these changes
I have built the project on Fedora 40 (using the default configuration) and I have verified that the built shared object links to /lib64/libpcre2-8.so.0.

LGTM. Can you mark it as ready to merge?

2024-06-05 13:11 UTC, Mab879 commented
> I have built the project on Fedora 40 (using the default configuration) and I have verified that the built shared object links to /lib64/libpcre2-8.so.0.
> 
> LGTM. Can you mark it as ready to merge?

Done.

2024-06-05 13:47 UTC, jan-cerny commented
CI fail on Fedora Latest isn't caused by this PR and will be fixed in https://github.com/OpenSCAP/openscap/pull/2118 and Packit jobs on CS 8 fail because CS 8 has been sunset.

2024-06-05 13:48 UTC, merged